import = [
  #optdaytime# "$alacritty_config_dir/alacritty-theme/themes/catppuccin_latte.toml",
  #optdaytime# "$alacritty_config_dir/alacritty-theme/themes/high_contrast.toml",
  #optdaytime# "$alacritty_config_dir/alacritty-theme/themes/night_owlish_light.toml",
  #optdarkmode#" $alacritty_config_dir/alacritty-theme/themes/gruvbox_dark.toml"
  #optdarkmode#" $alacritty_config_dir/alacritty-theme/themes/catppuccin.toml",
  #optdarkmode#" $alacritty_config_dir/alacritty-theme/themes/tokyo-night-storm.toml",
  ---
  #daytime# "$alacritty_config_dir/alacritty-theme/themes/rose-pine-dawn.toml",
  "$alacritty_config_dir/alacritty-theme/themes/dracula.toml",
]

[window]
padding = { x = 15, y = 15 }
decorations = "Buttonless"
dynamic_title = true
opacity = 1.0
blur = true

[font]
size = 13.0
normal = { family = "MesloLGSDZ Nerd Font Mono", style = "Regular" }

[mouse]
hide_when_typing = true 

[keyboard]
# codepoints.net are useful for finding the unicode
# the `showkey` tool is useful for visualizing keystrokes
bindings = [
  # these are to get my favorite programmable keymaps onto my laptop within the terminal
  { key = "K", mods = "Control", chars = "\u001b[A" }, #<ESC>[A 'up'
  { key = "J", mods = "Control", chars = "\u001b[B" }, #<ESC>[B 'down'
  # collides with previous item in lua snip # { key = "H", mods = "Control", chars = "\u001b[D" }, #<ESC>[D 'left'
  # collids with next item in lua snip # { key = "L", mods = "Control", chars = "\u001b[C" }, #<ESC>[C 'right'
  # nice word jump remaps for moving by word on the command line
  { key = "H", mods = "Control|Shift", chars = "\u001bB" }, # <ESC>B
  { key = "L", mods = "Control|Shift", chars = "\u001bF" }, # <ESC>F
  # custom things
  { key = "H", mods = "Control|Command", action = "HideOtherApplications"},
  { key = "U", mods = "Command", command = { program = "python3", args = ["$alacritty_config_dir/set_opacity.py"] } },
  { key = "I", mods = "Command", command = { program = "python3", args = ["$alacritty_config_dir/set_blur.py"] } },
]
