import = [
  #"$alacritty_config_dir/alacritty-theme/themes/high_contrast.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/night_owlish_light.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/github_light_high_contrast.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/github_light_colorblind.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/ayu_light.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/gruvbox_dark.toml"
  #"$alacritty_config_dir/alacritty-theme/themes/catppuccin.toml",
  "$alacritty_config_dir/alacritty-theme/themes/tokyo-night-storm.toml", #theme_choice 0
  #"$alacritty_config_dir/alacritty-theme/themes/catppuccin_latte.toml", #theme_choice 2
  #"$alacritty_config_dir/alacritty-theme/themes/rose-pine-dawn.toml", #theme_choice 1
  #"$alacritty_config_dir/alacritty-theme/themes/papercolor_light.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/pencil_light.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/noctis-lux.toml",
  #"$alacritty_config_dir/alacritty-theme/themes/dracula.toml", #theme_choice 3
]

live_config_reload = true

[window]
padding = { x = 5, y = 5 }
decorations = "Buttonless"
dynamic_title = true
title = ""
opacity = 0.9
blur = true

[bell]
duration = 0

[font]
size = 13.0
normal = { family = "MesloLGSDZ Nerd Font Mono", style = "Regular" }
builtin_box_drawing = true 

[mouse]
hide_when_typing = true 

[cursor]
style = { shape = "Underline", blinking = "Off" }
thickness = 0.35

[keyboard]
# codepoints.net are useful for finding the unicode
# the `showkey` tool is useful for visualizing keystrokes
bindings = [
  # these are to get my favorite programmable keymaps onto my laptop within the terminal
  { key = "K", mods = "Control", chars = "\u001b[A" }, #<ESC>[A 'up'
  { key = "J", mods = "Control", chars = "\u001b[B" }, #<ESC>[B 'down'
  # collides with previous item in lua snip # { key = "H", mods = "Control", chars = "\u001b[D" }, #<ESC>[D 'left'
  # collids with next item in lua snip # { key = "L", mods = "Control", chars = "\u001b[C" }, #<ESC>[C 'right'
  # nice word jump remaps for moving by word on the command line
  { key = "H", mods = "Control|Shift", chars = "\u001bB" }, # <ESC>B
  { key = "L", mods = "Control|Shift", chars = "\u001bF" }, # <ESC>F
  # custom things
  { key = "H", mods = "Control|Command", action = "HideOtherApplications"},
  { key = "U", mods = "Command", command = { program = "python3", args = ["$alacritty_config_dir/set_opacity.py"] } },
  { key = "I", mods = "Command", command = { program = "python3", args = ["$alacritty_config_dir/set_blur.py"] } },
  { key = "L", mods = "Command", command = { program = "python3", args = ["$alacritty_config_dir/set_theme.py"] } },
]
